= PiAware Parser 
joshua.faust@sevrosecurity.com
:toc:

If you're using dump1090-fa on a Raspberry Pi to track aircraft movement, this package allows you to save aircraft information to your local system as well as enrich your data with the https://rapidapi.com/adsbx/api/adsbexchange-com1/pricing[ADSBechanage API].

== How it works

Flight aware uses a dynamic json file `/run/dump1090-fa/aircraft.json` which is the base information you will see within your SkyAware Web dashboard. This package reads the data from the file, writes the data to a persistent gzipped CSV file, and continually checks for changes within `aircraft.json`. 

Essentially:

. Read `aircraft.json`
. Check if user has requested to use https://rapidapi.com/adsbx/api/adsbexchange-com1/pricing[ADSBexchange API].
.. This is to enrich the data if you do have access. 
. Write GZIPPED CSV data to a persistent file.
.. Filename is: `aircraft_<date>.csv.gz`
. Check if `aircraft.json` has new data.

== ADSBexchange API Feature

This package can use this api to add the following data points for each flight seen:

* flight Number
* Aircraft Registration
* Aircraft Type
* Is it Military
* Country of Origin

If you have an API key, use the `enrichment_api.conf` to hold your value.

== How to use

* Python 3.8+
* `pip install -r requirements.txt`

[source, text]
----
usage: backup_aircraft.py [-h] [-a]

optional arguments:
  -h, --help    show this help message and exit
  -a, --useapi  Use the FlightAware V3 api to enrich aircraft data
----


